### ISSUE TITLE
TALA_DG test case is incorrectly set up

### ISSUE THREAD

**Issue by Patol75** [g-adopt/g-adopt#111]
In the current TALA_DG test case, the reference viscosity profile is given in the [`StokesSolver`](https://github.com/g-adopt/g-adopt/blob/c0d298688b0c1fbf5f4ad92c550dc90d3fa93018/tests/2d_cylindrical_TALA_DG/2d_cylindrical_TALA_DG.py#L208-L210) call, but it is omitted in the [`TruncatedAnelasticLiquidApproximation`](https://github.com/g-adopt/g-adopt/blob/c0d298688b0c1fbf5f4ad92c550dc90d3fa93018/tests/2d_cylindrical_TALA_DG/2d_cylindrical_TALA_DG.py#L125) call. The consequence is an incorrect viscosity value in `viscous_dissipation`. The structure of the test case needs to be updated to account for this change. An example can be found [here](https://github.com/g-adopt/g-adopt/blob/update_approx/tests/2d_cylindrical_TALA_DG/2d_cylindrical_TALA_DG.py).

**Comment by drhodrid** [comment]
Thanks for this Thomas. This was a really important spot, and it turns out it makes quite the difference to some of our global simulations! I will push a change to address this in the coming days.
