### ISSUE TITLE
Parallel reproducibility issue of Cylindrical TALA DG case

### ISSUE THREAD

**Issue by angus-g** [g-adopt/g-adopt#123]
When we run this case in parallel, we get different answers to serial. Previously, some parallel reproducibility issues were due to MUMPS and direct solves, but given this case is cylindrical, it defaults to an iterative solver.

| &nbsp; | `u_rms` | `nu_top` | `avg_t` | `FullT_min` | `FullT_max` |
| --- | --- | --- | --- | --- | --- |
| actual | 570.5405141652053 | 15.186137483046036 | 0.6363851935782374 | 0.0001693939995075 | 1.0011846065377914 |
| expected | 570.4729595213425 | 15.18647692671351 | 0.6363801581209881 | 0.0001688057305039 |1.0011841176113832 |
| relative error | **1.18404639e-04** | **2.23517060e-05** | 7.91259335e-06 | **3.47278537e-03** | 4.88347908e-07 |

Noting that the relative error tolerance is 1e-5 by default, and we only override that to 1e-4 in the `3d_cartesian` case.

_Originally posted by @angus-g in https://github.com/g-adopt/g-adopt/issues/112#issuecomment-2367174471_

**Comment by Patol75** [comment]
Given the discussion in gh-124, this reproducibility issue likely arises from solver tolerances that were loosened too much.
