### ISSUE TITLE
issue at Davies_etal_GMD_2021/2D_cartesian/base_case_dpc/base_case_dpc.py

### ISSUE THREAD

**Issue by karimnorouzi** [g-adopt/g-adopt#14]
In this example, with my configuration of firedrake (installed on ubuntu 22) there is an error when setting up the solvers:

# Setup problem and solver objects so we can reuse (cache) solver setup
stokes_problem = NonlinearVariationalProblem(F_stokes, z, bcs=[bcvx, bcvy])

results in an error:

ValueError: Taking derivative of form wrt u, but form contains coefficients from u.subfunctions.
You probably meant to write split(u) when defining your form.

The complete error message is:

stokes_problem = NonlinearVariationalProblem(F_stokes, z, bcs=[bcvx, bcvy])
Traceback (most recent call last):

  Cell In[64], line 1
    stokes_problem = NonlinearVariationalProblem(F_stokes, z, bcs=[bcvx, bcvy])

  File petsc4py/PETSc/Log.pyx:115 in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func

  File petsc4py/PETSc/Log.pyx:116 in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func

  File ~/firedrake/src/pyadjoint/pyadjoint/tape.py:105 in wrapper
    return function(*args, **kwargs)

  File ~/firedrake/src/firedrake/firedrake/adjoint_utils/variational_solver.py:15 in wrapper
    init(self, *args, **kwargs)

  File ~/firedrake/src/firedrake/firedrake/variational_solver.py:80 in __init__
    self.J = J or ufl_expr.derivative(F, u)

  File petsc4py/PETSc/Log.pyx:115 in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func

  File petsc4py/PETSc/Log.pyx:116 in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func

  File ~/firedrake/src/firedrake/firedrake/ufl_expr.py:153 in derivative
    raise ValueError("Taking derivative of form wrt u, but form contains coefficients from u.subfunctions."

ValueError: Taking derivative of form wrt u, but form contains coefficients from u.subfunctions.
You probably meant to write split(u) when defining your form.

why it is not working ?

**Comment by stephankramer** [comment]
It looks like you are using a `u_` or a `p_` in your F_stokes that comes from:
```
u_, p_ = z.split()
```
or equivalently
```
u_, p_ = z.subfunctions
```
This way of extracting the velocity and pressure from the combined velocity pressure solution `z` is useful e.g. for outputting to files or other places where you want to use these solution results as separate functions - but they should *not* be used in symbolic expressions like `F_stokes`.

To refer to the velocity or pressure in symbolic expressions you should use the `u` and `p` that come from
```
u, p = split(z)
```

To minimize the confusion in our setups we tend to use `u_, p_` for the former (`z.subfunctions`), and `u, p` for the latter  (from `split(z)`) - but this is of course just a convention you can name it anything...

**Comment by stephankramer** [comment]
Oh sorry I see you are referring to a specific case (in which we didn't follow the convection!). Did you make any changes to that base_case_dpc.py? It runs fine for me.
