### ISSUE TITLE
body force 

### ISSUE THREAD

**Issue by karimnorouzi** [g-adopt/g-adopt#16]
Hi, I was wondering why the gravity body force is missing in the weak form for the Spiegelman Example ?

**Comment by stephankramer** [comment]
For the Spiegelman case the density is the same everywhere in the domain and thus if you separate the lithostatic pressure from the equations (cf. eqns (22) and (23) in Spiegelman, with rho=rho0 everywhere) there is no remaining force term on the rhs. This separation also means we can separately p_lith calculate in a prescribed way (independent of the solution), and the p that we solve for in the Stokes system is the dynamic pressure deviation that is added on to that, which is then used in the plastic viscosity (eqn (21) in Spiegelman)

**Comment by stephankramer** [comment]
Even with varying densities, you typically still want to subtract a reference pressure profile.

You could apply a pressure, or more correctly a normal stress boundary condition at the top, but that would imply that you leave the normal component of velocity free. In a typical geodynamical application that would lead to dynamic topography with a lithostatic pressure that over a relatively short period of time equilibrates with the normal stress from the interior - if you're not resolving (in time) this relaxation to equilibrium, the best approximation is to assume this happens instantaneously which means the surface is assumed at rest which leads to a no normal velocity (Dirichlet) condition. If you do want to track the movement of the surface, and leave the normal component of velocity free you need to implement a free surface mechanism or move your mesh nodes.

**Comment by karimnorouzi** [comment]
I am a bit confused.  I use Lagrangian description of the fluid flow for my domain, ( Stoks flow, rift margin simulation).  I have prescribed velocity at left and right (Dirichlet). I want to apply isostatic pressure at the bottom as Neuman boundary, 
and at the top boundary, n.u  = 0 (n surface normal and u is velocity). Why do I need to track my surface boundray ? all the nodes will move as well as surface boundary nodes.
