### ISSUE TITLE
matplotlib's lock file  on gadi

### ISSUE THREAD

**Issue by sghelichkhani** [g-adopt/g-adopt#20]
This has occurred to a few of us that when running firedrake on NCI's gadi, we get an error like 

```
TimeoutError: Lock error: Matplotlib failed to acquire the following lock file:
    /jobfs/95688198.gadi-pbs/xdg/matplotlib/fontlist-v330.json.matplotlib-lock
This maybe due to another process holding this lock file.  If you are sure no
other Matplotlib process is running, remove this file and try again.
```

The error message indicates that multiple processes are trying to access the same lock file which is simply because multiple processes  are trying to import matplotlib simultaneously. The lock is used to prevent multiple processes from writing to the cache simultaneously.

A combination of these two before running the firedrake script should prevent the issue
```bash
export MPLCONFIGDIR=${PBS_JOBFS}/MPL_DIR
mpiexec --map-by ppr:1:node -np $PBS_NNODES  python3 -c "import matplotlib.pyplot as plt"
```

**Comment by angus-g** [comment]
Moved to a [wiki page](https://github.com/g-adopt/g-adopt/wiki/Common-Issues)
