### ISSUE TITLE
Performance of GAMG

### ISSUE THREAD

**Issue by drhodrid** [g-adopt/g-adopt#29]
Coarsening strategies for GAMG (or MG in general) have been updated by PETSc. With recent PETSc versions, we are currently unable to replicate the parallel scaling performance showcased in Davies et al. 2022 (GMD) (and memory requirements have increased substantially). Working on this: discussion thread here: https://lists.mcs.anl.gov/pipermail/petsc-users/2023-October/049592.html

**Comment by angus-g** [comment]
Follow-on effect: the spherical adaptive cases #26 won't run at level 7.

**Comment by angus-g** [comment]
So the relevant changes for this have landed upstream, and we have an in-progress PR Firedrake's fork: https://github.com/firedrakeproject/petsc/pull/16
