### ISSUE TITLE
DG Energy Solve with SU_advection = True

### ISSUE THREAD

**Issue by drhodrid** [g-adopt/g-adopt#62]
I recently (accidentally) ran a case with a DG approach for the energy solve, but forgot to remove the su_advection = True flag. I'm unsure what this would've done (!), but it's probably wise to add some sort of options check to ensure that others don't make the same mistake. Thoughts?

**Comment by w3168** [comment]
Ah yeah I probably should put an assert in to make sure that it's only on the right function spaces

**Comment by drhodrid** [comment]
I mean it was also a silly mistake on my part, but probably good to get an assert in, just to be safe!!

----------------------------------------------------------------------------------------------------------
Professor (Computational & Observational Geodynamics)
Associate Director Research & Engagement
Research School of Earth Sciences,
The Australian National University,
Mills Road, Acton,
Canberra, ACT, 2601, Australia

T: +61 (0)2 6125 3643
E: ***@***.***
W: https://earthsciences.anu.edu.au/people/academics/professor-rhodri-davies
CRICOS Provider No. 00120C
----------------------------------------------------------------------------------------------------------

On 8 Apr 2024, at 10:00 AM, Will Scott ***@***.***> wrote:



Ah yeah I probably should put an assert in to make sure that it's only on the right function spaces
